In [27]:
import tensorflow as tf

In [28]:
import numpy as np

In [20]:
def getLotto(link):
    df = pd.read_excel(link, index_col=0)
    df.drop(columns=['Hét', 'Húzásdátum', '6 találat (db)', '6 találat (Ft)',
       '5+1 találat (db)', '5+1 találat (Ft)', '5 találat (db)',
       '5 találat (Ft)', '4 találat (db)', '4 találat (Ft)', '3 találat (db)',
       '3 találat (Ft)', "Unnamed: 19"], inplace=True)
    
    df.rename(columns={"Számok": "1", "Unnamed: 14": "2", "Unnamed: 15": "3", 'Unnamed: 16':"4", "Unnamed: 17":"5", "Unnamed: 18": "6"}, inplace=True)
    column_values = df[["1", "2", "3", "4", "5", "6"]].values
    return df, column_values

In [21]:
link = "https://bet.szerencsejatek.hu/cmsfiles/hatos.xls"
df, dfRaw = getLotto(link)

In [24]:
dfRaw[0]

array([ 7, 11, 15, 18, 19, 32], dtype=int64)

In [26]:
pd.get_dummmies(dfRaw)

AttributeError: module 'pandas' has no attribute 'get_dummmies'

In [31]:
one_hot_encoded = tf.one_hot(dfRaw, depth=45)

In [38]:
one_hot_encoded

<tf.Tensor: shape=(1630, 6, 45), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0.,

In [34]:
#merged_array = tf.reduce_sum(one_hot_encoded, axis=0)

In [42]:
merged_array = tf.reduce_max(one_hot_encoded, axis=1)


<tf.Tensor: shape=(45,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>